/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicarRouteImport } from './routes/publicar'
import { Route as PlanosRouteImport } from './routes/planos'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as MapaRouteImport } from './routes/mapa'
import { Route as InspiracaoRouteImport } from './routes/inspiracao'
import { Route as FaturasRouteImport } from './routes/faturas'
import { Route as ExplorarRouteImport } from './routes/explorar'
import { Route as EmergenciaRouteImport } from './routes/emergencia'
import { Route as CriarPostRouteImport } from './routes/criar-post'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AgendamentosRouteImport } from './routes/agendamentos'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChatIndexRouteImport } from './routes/chat.index'
import { Route as PerfilIdRouteImport } from './routes/perfil.$id'
import { Route as ChatIdRouteImport } from './routes/chat.$id'
import { Route as ChamadaIdRouteImport } from './routes/chamada.$id'

const PublicarRoute = PublicarRouteImport.update({
  id: '/publicar',
  path: '/publicar',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanosRoute = PlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const MapaRoute = MapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => rootRouteImport,
} as any)
const InspiracaoRoute = InspiracaoRouteImport.update({
  id: '/inspiracao',
  path: '/inspiracao',
  getParentRoute: () => rootRouteImport,
} as any)
const FaturasRoute = FaturasRouteImport.update({
  id: '/faturas',
  path: '/faturas',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorarRoute = ExplorarRouteImport.update({
  id: '/explorar',
  path: '/explorar',
  getParentRoute: () => rootRouteImport,
} as any)
const EmergenciaRoute = EmergenciaRouteImport.update({
  id: '/emergencia',
  path: '/emergencia',
  getParentRoute: () => rootRouteImport,
} as any)
const CriarPostRoute = CriarPostRouteImport.update({
  id: '/criar-post',
  path: '/criar-post',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendamentosRoute = AgendamentosRouteImport.update({
  id: '/agendamentos',
  path: '/agendamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilIdRoute = PerfilIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PerfilRoute,
} as any)
const ChatIdRoute = ChatIdRouteImport.update({
  id: '/chat/$id',
  path: '/chat/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ChamadaIdRoute = ChamadaIdRouteImport.update({
  id: '/chamada/$id',
  path: '/chamada/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/agendamentos': typeof AgendamentosRoute
  '/auth': typeof AuthRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/criar-post': typeof CriarPostRoute
  '/emergencia': typeof EmergenciaRoute
  '/explorar': typeof ExplorarRoute
  '/faturas': typeof FaturasRoute
  '/inspiracao': typeof InspiracaoRoute
  '/mapa': typeof MapaRoute
  '/perfil': typeof PerfilRouteWithChildren
  '/planos': typeof PlanosRoute
  '/publicar': typeof PublicarRoute
  '/chamada/$id': typeof ChamadaIdRoute
  '/chat/$id': typeof ChatIdRoute
  '/perfil/$id': typeof PerfilIdRoute
  '/chat/': typeof ChatIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/agendamentos': typeof AgendamentosRoute
  '/auth': typeof AuthRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/criar-post': typeof CriarPostRoute
  '/emergencia': typeof EmergenciaRoute
  '/explorar': typeof ExplorarRoute
  '/faturas': typeof FaturasRoute
  '/inspiracao': typeof InspiracaoRoute
  '/mapa': typeof MapaRoute
  '/perfil': typeof PerfilRouteWithChildren
  '/planos': typeof PlanosRoute
  '/publicar': typeof PublicarRoute
  '/chamada/$id': typeof ChamadaIdRoute
  '/chat/$id': typeof ChatIdRoute
  '/perfil/$id': typeof PerfilIdRoute
  '/chat': typeof ChatIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/agendamentos': typeof AgendamentosRoute
  '/auth': typeof AuthRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/criar-post': typeof CriarPostRoute
  '/emergencia': typeof EmergenciaRoute
  '/explorar': typeof ExplorarRoute
  '/faturas': typeof FaturasRoute
  '/inspiracao': typeof InspiracaoRoute
  '/mapa': typeof MapaRoute
  '/perfil': typeof PerfilRouteWithChildren
  '/planos': typeof PlanosRoute
  '/publicar': typeof PublicarRoute
  '/chamada/$id': typeof ChamadaIdRoute
  '/chat/$id': typeof ChatIdRoute
  '/perfil/$id': typeof PerfilIdRoute
  '/chat/': typeof ChatIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/agendamentos'
    | '/auth'
    | '/configuracoes'
    | '/criar-post'
    | '/emergencia'
    | '/explorar'
    | '/faturas'
    | '/inspiracao'
    | '/mapa'
    | '/perfil'
    | '/planos'
    | '/publicar'
    | '/chamada/$id'
    | '/chat/$id'
    | '/perfil/$id'
    | '/chat/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/agendamentos'
    | '/auth'
    | '/configuracoes'
    | '/criar-post'
    | '/emergencia'
    | '/explorar'
    | '/faturas'
    | '/inspiracao'
    | '/mapa'
    | '/perfil'
    | '/planos'
    | '/publicar'
    | '/chamada/$id'
    | '/chat/$id'
    | '/perfil/$id'
    | '/chat'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/agendamentos'
    | '/auth'
    | '/configuracoes'
    | '/criar-post'
    | '/emergencia'
    | '/explorar'
    | '/faturas'
    | '/inspiracao'
    | '/mapa'
    | '/perfil'
    | '/planos'
    | '/publicar'
    | '/chamada/$id'
    | '/chat/$id'
    | '/perfil/$id'
    | '/chat/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AgendamentosRoute: typeof AgendamentosRoute
  AuthRoute: typeof AuthRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  CriarPostRoute: typeof CriarPostRoute
  EmergenciaRoute: typeof EmergenciaRoute
  ExplorarRoute: typeof ExplorarRoute
  FaturasRoute: typeof FaturasRoute
  InspiracaoRoute: typeof InspiracaoRoute
  MapaRoute: typeof MapaRoute
  PerfilRoute: typeof PerfilRouteWithChildren
  PlanosRoute: typeof PlanosRoute
  PublicarRoute: typeof PublicarRoute
  ChamadaIdRoute: typeof ChamadaIdRoute
  ChatIdRoute: typeof ChatIdRoute
  ChatIndexRoute: typeof ChatIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/publicar': {
      id: '/publicar'
      path: '/publicar'
      fullPath: '/publicar'
      preLoaderRoute: typeof PublicarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos': {
      id: '/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof PlanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapa': {
      id: '/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof MapaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspiracao': {
      id: '/inspiracao'
      path: '/inspiracao'
      fullPath: '/inspiracao'
      preLoaderRoute: typeof InspiracaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faturas': {
      id: '/faturas'
      path: '/faturas'
      fullPath: '/faturas'
      preLoaderRoute: typeof FaturasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorar': {
      id: '/explorar'
      path: '/explorar'
      fullPath: '/explorar'
      preLoaderRoute: typeof ExplorarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emergencia': {
      id: '/emergencia'
      path: '/emergencia'
      fullPath: '/emergencia'
      preLoaderRoute: typeof EmergenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/criar-post': {
      id: '/criar-post'
      path: '/criar-post'
      fullPath: '/criar-post'
      preLoaderRoute: typeof CriarPostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agendamentos': {
      id: '/agendamentos'
      path: '/agendamentos'
      fullPath: '/agendamentos'
      preLoaderRoute: typeof AgendamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/': {
      id: '/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil/$id': {
      id: '/perfil/$id'
      path: '/$id'
      fullPath: '/perfil/$id'
      preLoaderRoute: typeof PerfilIdRouteImport
      parentRoute: typeof PerfilRoute
    }
    '/chat/$id': {
      id: '/chat/$id'
      path: '/chat/$id'
      fullPath: '/chat/$id'
      preLoaderRoute: typeof ChatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chamada/$id': {
      id: '/chamada/$id'
      path: '/chamada/$id'
      fullPath: '/chamada/$id'
      preLoaderRoute: typeof ChamadaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PerfilRouteChildren {
  PerfilIdRoute: typeof PerfilIdRoute
}

const PerfilRouteChildren: PerfilRouteChildren = {
  PerfilIdRoute: PerfilIdRoute,
}

const PerfilRouteWithChildren =
  PerfilRoute._addFileChildren(PerfilRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AgendamentosRoute: AgendamentosRoute,
  AuthRoute: AuthRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  CriarPostRoute: CriarPostRoute,
  EmergenciaRoute: EmergenciaRoute,
  ExplorarRoute: ExplorarRoute,
  FaturasRoute: FaturasRoute,
  InspiracaoRoute: InspiracaoRoute,
  MapaRoute: MapaRoute,
  PerfilRoute: PerfilRouteWithChildren,
  PlanosRoute: PlanosRoute,
  PublicarRoute: PublicarRoute,
  ChamadaIdRoute: ChamadaIdRoute,
  ChatIdRoute: ChatIdRoute,
  ChatIndexRoute: ChatIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
